type TrackPreset = {
  id: string;
  group: "core" | "specialization";
  title: string;
  topic: string;
  level: "beginner" | "intermediate" | "advanced" | "expert";
  audience: string;
  prerequisites: string;
  curriculumRules: readonly string[];
  goal: string;
  description: string;
};

const specializationBase = {
  group: "specialization" as const,
  level: "advanced" as const,
};

export const trackPresets: readonly TrackPreset[] = [
  {
    id: "cpp-unreal-basic",
    group: "core",
    title: "C++ + Unreal: Do Zero",
    topic: "Fundamentos de programação, C++ e Unreal Engine 5",
    level: "beginner",
    audience: "Pessoa que nunca programou e nunca utilizou C++ ou Unreal Engine.",
    prerequisites: "Nenhum. Não assumir conhecimento de lógica, compilação, C++, orientação a objetos ou Unreal.",
    curriculumRules: [
      "Começar explicando programação, código-fonte, compilação, programa e erro.",
      "Ensinar anatomia do código, tipos, variáveis, operadores, controle de fluxo e funções.",
      "Ensinar orientação a objetos, ponteiros, referências e arquivos .h e .cpp antes da Unreal.",
      "Introduzir Unreal somente depois da base necessária de C++, explicando cada termo e macro.",
    ],
    goal: "Sair do zero absoluto e conseguir compreender, escrever e explicar pequenos sistemas de gameplay em C++ para Unreal Engine 5.",
    description: "Programação do zero, fundamentos de C++, anatomia da Unreal e primeiros sistemas.",
  },
  {
    id: "cpp-unreal-intermediate",
    group: "core",
    title: "C++ + Unreal: Intermediário",
    topic: "Desenvolvimento intermediário em C++ para Unreal Engine 5",
    level: "intermediate",
    audience: "Pessoa que concluiu a trilha C++ + Unreal: Do Zero.",
    prerequisites: "Fundamentos de C++, orientação a objetos, Actor, componentes, UPROPERTY e UFUNCTION.",
    curriculumRules: [
      "Partir da trilha Do Zero e revisar dependências antes de ampliá-las.",
      "Ensinar containers, enums, delegates, interfaces e composição antes de depender deles.",
      "Explicar o gameplay framework antes de distribuir lógica entre suas classes.",
      "Construir sistemas completos de dificuldade crescente e explicar decisões de arquitetura.",
    ],
    goal: "Construir sistemas de gameplay reutilizáveis, desacoplados e bem organizados.",
    description: "Containers, delegates, interfaces, gameplay framework e sistemas reutilizáveis.",
  },
  {
    id: "cpp-unreal-advanced",
    group: "core",
    title: "C++ + Unreal: Avançado",
    topic: "Arquitetura avançada e engenharia de gameplay em C++ para Unreal Engine 5",
    level: "advanced",
    audience: "Pessoa que concluiu as trilhas C++ + Unreal: Do Zero e Intermediário.",
    prerequisites: "C++ intermediário, containers, delegates, interfaces, gameplay framework, depuração e desacoplamento.",
    curriculumRules: [
      "Partir da trilha intermediária e reintroduzir o contexto antes de cada conceito avançado.",
      "Ensinar memória, ciclo de vida e garbage collection antes de decisões complexas.",
      "Ensinar subsystems, assets orientados a dados, assíncrono, profiling e otimização incrementalmente.",
      "Explicar trade-offs, riscos e alternativas de cada decisão arquitetural.",
    ],
    goal: "Projetar, diagnosticar e evoluir sistemas robustos, escaláveis e preparados para produção.",
    description: "Memória, subsystems, arquitetura orientada a dados, assíncrono, profiling e otimização.",
  },
  {
    ...specializationBase,
    id: "unreal-multiplayer",
    title: "Multiplayer e Replicação",
    topic: "Multiplayer e replicação em C++ para Unreal Engine 5",
    audience: "Pessoa que concluiu ao menos a trilha intermediária.",
    prerequisites: "Gameplay framework, componentes, interfaces, delegates, eventos e depuração.",
    curriculumRules: ["Partir de sistemas single-player.", "Ensinar cliente-servidor, autoridade e estado antes de replicação.", "Ensinar propriedades replicadas antes de RPCs."],
    goal: "Construir mecânicas multiplayer corretas, previsíveis e diagnosticáveis.",
    description: "Autoridade, RPCs, replicação, relevância, estados e debugging.",
  },
  {
    ...specializationBase,
    id: "unreal-gas",
    title: "Gameplay Ability System",
    topic: "Gameplay Ability System em C++ para Unreal Engine 5",
    audience: "Pessoa que concluiu a trilha avançada e possui fundamentos de multiplayer.",
    prerequisites: "C++ avançado, componentes, interfaces, delegates, arquitetura orientada a dados e multiplayer.",
    curriculumRules: ["Apresentar arquitetura e fluxo de dados antes das APIs.", "Ensinar tags, attributes, effects e abilities separadamente.", "Construir um sistema testável em cada etapa."],
    goal: "Projetar e implementar sistemas de habilidades escaláveis com GAS.",
    description: "Abilities, effects, attributes, tags, custos, cooldowns e arquitetura GAS.",
  },
  {
    ...specializationBase,
    id: "unreal-ai",
    title: "Inteligência Artificial",
    topic: "Inteligência artificial de gameplay em C++ para Unreal Engine 5",
    audience: "Pessoa que domina gameplay framework e sistemas intermediários.",
    prerequisites: "Pawns, Controllers, componentes, delegates, interfaces e depuração.",
    curriculumRules: ["Explicar percepção, decisão e ação antes das ferramentas.", "Ensinar AIController, NavMesh e percepção antes de Behavior Trees e EQS.", "Construir inimigos progressivamente."],
    goal: "Criar agentes, inimigos e comportamentos de IA modulares e diagnosticáveis.",
    description: "AIController, percepção, navegação, Behavior Trees, EQS e combate.",
  },
  {
    ...specializationBase,
    id: "unreal-inventory",
    title: "Inventário e Itens",
    topic: "Sistemas de inventário e itens em C++ para Unreal Engine 5",
    audience: "Pessoa que concluiu a trilha intermediária.",
    prerequisites: "Structs, containers, componentes, interfaces, delegates e Data Assets.",
    curriculumRules: ["Modelar item, instância, pilha e inventário separadamente.", "Separar dados estáticos de estado mutável.", "Evoluir para equipamentos, uso, troca e UI."],
    goal: "Construir um sistema de itens e inventário reutilizável e orientado a dados.",
    description: "Itens, stacks, equipamentos, Data Assets, interação e integração com UI.",
  },
  {
    ...specializationBase,
    id: "unreal-save-system",
    title: "Save System e Persistência",
    topic: "Persistência e save systems em C++ para Unreal Engine 5",
    audience: "Pessoa que já constrói sistemas orientados a dados.",
    prerequisites: "Structs, containers, interfaces, identificação de entidades e arquitetura desacoplada.",
    curriculumRules: ["Distinguir configuração, sessão e estado persistente.", "Ensinar serialização e identificação antes de saves complexos.", "Cobrir versionamento, migração e falhas."],
    goal: "Criar persistência robusta, versionável e preparada para evolução.",
    description: "SaveGame, serialização, IDs, slots, versionamento, migração e carregamento.",
  },
  {
    ...specializationBase,
    id: "unreal-ui",
    title: "UI, UMG e CommonUI",
    topic: "Interfaces de usuário em C++ com UMG e CommonUI",
    audience: "Pessoa que domina eventos, componentes e comunicação entre sistemas.",
    prerequisites: "Delegates, interfaces, PlayerController e dados orientados a eventos.",
    curriculumRules: ["Separar estado, apresentação e entrada.", "Ensinar ciclo de vida de widgets antes de navegação.", "Evoluir HUD simples para menus reutilizáveis."],
    goal: "Construir interfaces responsivas, desacopladas e preparadas para diferentes entradas.",
    description: "UMG, widgets, HUD, menus, navegação, input e CommonUI.",
  },
  {
    ...specializationBase,
    id: "unreal-animation",
    title: "Animação de Gameplay",
    topic: "Sistemas de animação orientados por C++ na Unreal Engine 5",
    audience: "Pessoa que domina personagens, componentes e gameplay intermediário.",
    prerequisites: "Character, movimento, eventos, interfaces, delegates e vetores.",
    curriculumRules: ["Explicar dados de movimento e pose antes de state machines.", "Ensinar Animation Blueprint, montages e notifies separadamente.", "Manter animação e gameplay desacoplados."],
    goal: "Integrar movimento, combate e feedback visual com animações robustas.",
    description: "Animation Blueprint, state machines, montages, notifies e gameplay.",
  },
  {
    ...specializationBase,
    id: "unreal-architecture",
    title: "Arquitetura e Padrões",
    topic: "Arquitetura e padrões de projeto aplicados à Unreal Engine 5",
    audience: "Pessoa que já construiu diferentes sistemas de gameplay.",
    prerequisites: "Interfaces, delegates, componentes, subsystems, gameplay framework e desacoplamento.",
    curriculumRules: ["Partir de problemas concretos antes de padrões.", "Explicar custo, benefício e sinais de uso incorreto.", "Refatorar sistemas acoplados incrementalmente."],
    goal: "Tomar decisões arquiteturais conscientes e manter projetos grandes evolutivos.",
    description: "Composição, eventos, subsystems, padrões, modularidade e refatoração.",
  },
  {
    ...specializationBase,
    id: "unreal-performance",
    title: "Performance e Otimização",
    topic: "Profiling e otimização de projetos C++ na Unreal Engine 5",
    audience: "Pessoa que domina C++ avançado e possui sistemas funcionais para medir.",
    prerequisites: "Ciclo de vida, memória, componentes, Tick, assíncrono e arquitetura.",
    curriculumRules: ["Medir antes de otimizar.", "Ensinar CPU, memória, renderização e carregamento separadamente.", "Validar cada otimização com evidências."],
    goal: "Diagnosticar gargalos e otimizar projetos com decisões baseadas em evidências.",
    description: "Unreal Insights, CPU, memória, Tick, carregamento, pooling e async.",
  },
  {
    ...specializationBase,
    id: "unreal-editor-tools",
    title: "Ferramentas do Editor",
    topic: "Ferramentas de produção e extensões do editor em C++",
    audience: "Pessoa que domina arquitetura, assets e fluxo de trabalho da Unreal.",
    prerequisites: "C++ avançado, módulos, assets, reflexão e arquitetura orientada a dados.",
    curriculumRules: ["Começar por automações pequenas.", "Separar runtime de editor antes de criar ferramentas.", "Construir ferramentas a partir de problemas reais."],
    goal: "Automatizar fluxos e criar ferramentas que acelerem equipes e reduzam erros.",
    description: "Editor modules, automação, validação, detalhes customizados e ferramentas internas.",
  },
];
