export type ReferenceCategory =
  | "C++ Base"
  | "Tipos e Variaveis"
  | "Operadores C++"
  | "Funcoes C++"
  | "Arquivos C++"
  | "Unreal Macros"
  | "Specifiers"
  | "Tipos Unreal"
  | "Actor Lifecycle"
  | "Transform"
  | "Math"
  | "Components"
  | "Collision"
  | "Input"
  | "Debug"
  | "Gameplay Framework"
  | "Containers"
  | "Memory";

export type ReferenceEntry = {
  slug: string;
  title: string;
  category: ReferenceCategory;
  summary: string;
  syntax: string;
  returns?: string;
  useWhen: string;
  example: string;
  pitfalls: string[];
  related: string[];
};

export const referenceCategories: ReferenceCategory[] = [
  "C++ Base",
  "Tipos e Variaveis",
  "Operadores C++",
  "Funcoes C++",
  "Arquivos C++",
  "Unreal Macros",
  "Specifiers",
  "Tipos Unreal",
  "Actor Lifecycle",
  "Transform",
  "Math",
  "Components",
  "Collision",
  "Input",
  "Debug",
  "Gameplay Framework",
  "Containers",
  "Memory",
];

export const referenceEntries: ReferenceEntry[] = [
  {
    slug: "class",
    title: "class",
    category: "C++ Base",
    summary: "Define um tipo próprio com dados e funções. Na Unreal, classes costumam representar Actors, Components, GameModes e objetos reutilizáveis.",
    syntax: "class AMyActor : public AActor { ... };",
    useWhen: "Use quando quiser criar uma entidade com comportamento e estado próprios.",
    example: "class AMyPickup : public AActor\n{\npublic:\n  void Activate();\n};",
    pitfalls: ["Esquecer o ponto e virgula depois do bloco da classe.", "Misturar nome da classe com nome do arquivo sem consistencia."],
    related: ["public", "private", "inheritance", "uclass"],
  },
  {
    slug: "inheritance",
    title: "Heranca",
    category: "C++ Base",
    summary: "Permite criar uma classe baseada em outra. Em Unreal, voce herda de AActor, APawn, UActorComponent e outras classes do framework.",
    syntax: "class AMyActor : public AActor",
    useWhen: "Use para reaproveitar comportamento de uma classe base da Unreal.",
    example: "class AFloatingPickup : public AActor\n{\n  GENERATED_BODY()\n};",
    pitfalls: ["Herdar da classe errada para o papel desejado.", "Esquecer includes da classe base."],
    related: ["class", "aactor", "uactorcomponent"],
  },
  {
    slug: "public-private-protected",
    title: "public / protected / private",
    category: "C++ Base",
    summary: "Controlam quem pode acessar membros da classe. Publico fica acessivel de fora, protected para a classe e filhas, private apenas dentro da propria classe.",
    syntax: "public:\nprotected:\nprivate:",
    useWhen: "Use para organizar API publica, pontos de extensao e detalhes internos.",
    example: "public:\n  virtual void Tick(float DeltaTime) override;\n\nprivate:\n  FVector InitialLocation;",
    pitfalls: ["Colocar dados internos como public sem necessidade.", "Declarar overrides em private quando a Unreal precisa chamar."],
    related: ["class", "override", "beginplay"],
  },
  {
    slug: "constructor",
    title: "Construtor",
    category: "C++ Base",
    summary: "Funcao chamada quando o objeto e criado. Na Unreal, e comum configurar valores padrao e criar componentes no construtor.",
    syntax: "AMyActor::AMyActor() { ... }",
    useWhen: "Use para definir estado inicial e componentes padrao.",
    example: "AMyActor::AMyActor()\n{\n  PrimaryActorTick.bCanEverTick = true;\n}",
    pitfalls: ["Tentar acessar o mundo ou outros Actors no construtor.", "Colocar logica de runtime que deveria estar em BeginPlay."],
    related: ["beginplay", "primaryactortick", "createdefaultsubobject"],
  },
  {
    slug: "override",
    title: "override",
    category: "C++ Base",
    summary: "Indica que uma funcao substitui uma funcao virtual da classe base. Ajuda o compilador a detectar assinaturas erradas.",
    syntax: "virtual void Tick(float DeltaTime) override;",
    useWhen: "Use ao reimplementar BeginPlay, Tick, SetupPlayerInputComponent e outras funcoes virtuais.",
    example: "virtual void BeginPlay() override;",
    pitfalls: ["Assinatura diferente da classe base impede o override.", "Remover virtual/override torna o erro menos claro."],
    related: ["beginplay", "tick", "setupplayerinputcomponent"],
  },
  {
    slug: "float",
    title: "float",
    category: "Tipos e Variaveis",
    summary: "Tipo numerico com casas decimais, muito usado para tempo, velocidade, distancia e interpolacoes.",
    syntax: "float Speed = 300.0f;",
    returns: "Um numero decimal de precisao simples.",
    useWhen: "Use para valores continuos como velocidade, amplitude, DeltaTime e multiplicadores.",
    example: "float ZOffset = FMath::Sin(RunningTime) * FloatAmplitude;",
    pitfalls: ["Esquecer o sufixo f em literais como 20.0f.", "Usar int quando precisa de movimento suave."],
    related: ["deltatime", "fmath-sin", "fvector"],
  },
  {
    slug: "int",
    title: "int",
    category: "Tipos e Variaveis",
    summary: "Tipo inteiro padrao do C++. Guarda numeros sem casas decimais, como contadores, indices e quantidades.",
    syntax: "int Count = 3;",
    returns: "Um numero inteiro. O tamanho exato pode variar por plataforma, por isso a Unreal costuma preferir tipos com tamanho fixo.",
    useWhen: "Use em C++ comum para contagens simples. Em codigo Unreal, prefira int32 quando o valor entra em APIs, propriedades ou dados persistidos.",
    example: "int Attempts = 0;\nAttempts += 1;",
    pitfalls: ["Usar int para valores que precisam ter tamanho garantido entre plataformas.", "Esperar casas decimais; divisao entre int descarta a parte fracionaria."],
    related: ["int32", "float", "for-loop"],
  },
  {
    slug: "int32",
    title: "int32",
    category: "Tipos e Variaveis",
    summary: "Inteiro assinado de 32 bits usado com frequencia na Unreal. Representa valores positivos e negativos sem casas decimais.",
    syntax: "int32 Score = 100;",
    returns: "Um inteiro de 32 bits, normalmente de -2.147.483.648 a 2.147.483.647.",
    useWhen: "Use para pontuacao, quantidade, indices, vida inteira, contadores e propriedades numericas comuns em Unreal.",
    example: "UPROPERTY(EditAnywhere, Category=\"Score\")\nint32 PointsToAdd = 10;",
    pitfalls: ["Usar para dinheiro, tempo ou interpolacao que precisam de decimais.", "Estourar o limite em acumuladores muito grandes."],
    related: ["int", "int64", "uint8", "uproperty"],
  },
  {
    slug: "uint8",
    title: "uint8",
    category: "Tipos e Variaveis",
    summary: "Inteiro sem sinal de 8 bits. Guarda valores pequenos de 0 a 255 e aparece bastante em enums refletidos da Unreal.",
    syntax: "uint8 Index = 0;",
    returns: "Um inteiro de 8 bits entre 0 e 255.",
    useWhen: "Use quando uma API exige byte ou ao declarar enum class refletido com base uint8.",
    example: "UENUM(BlueprintType)\nenum class EDoorState : uint8\n{\n  Closed,\n  Open\n};",
    pitfalls: ["Guardar valores acima de 255.", "Subtrair abaixo de zero em tipo sem sinal e causar volta de valor."],
    related: ["uenum", "int32", "bool"],
  },
  {
    slug: "uint32",
    title: "uint32",
    category: "Tipos e Variaveis",
    summary: "Inteiro sem sinal de 32 bits. Guarda apenas valores zero ou positivos, com limite maior que int32 no lado positivo.",
    syntax: "uint32 Flags = 0;",
    returns: "Um inteiro de 32 bits entre 0 e 4.294.967.295.",
    useWhen: "Use para bitmasks, flags e APIs que esperam explicitamente inteiro sem sinal.",
    example: "uint32 CollisionMask = 0;\nCollisionMask |= 1u << 2;",
    pitfalls: ["Usar para valores que podem ficar negativos.", "Misturar signed e unsigned em comparacoes sem perceber."],
    related: ["uint8", "int32", "bitmask"],
  },
  {
    slug: "bitmask",
    title: "Bitmask",
    category: "Operadores C++",
    summary: "Tecnica que usa bits individuais de um inteiro para guardar varias flags verdadeiro/falso no mesmo valor.",
    syntax: "Flags |= 1u << BitIndex;",
    returns: "Um inteiro onde cada bit pode representar uma opcao ligada ou desligada.",
    useWhen: "Use quando uma API trabalha com flags ou quando precisa combinar varias opcoes leves em um unico valor.",
    example: "uint32 Flags = 0;\nFlags |= 1u << 0;\nconst bool bHasFirstFlag = (Flags & (1u << 0)) != 0;",
    pitfalls: ["Usar bitmask quando varios bools deixariam o codigo mais claro.", "Errar o deslocamento e testar o bit errado."],
    related: ["uint32", "bool", "uenum"],
  },
  {
    slug: "int64",
    title: "int64",
    category: "Tipos e Variaveis",
    summary: "Inteiro assinado de 64 bits. Suporta numeros muito maiores que int32, ainda sem casas decimais.",
    syntax: "int64 TotalExperience = 0;",
    returns: "Um inteiro de 64 bits para contagens grandes.",
    useWhen: "Use para acumuladores grandes, timestamps, ids numericos e valores que podem passar do limite de int32.",
    example: "int64 TotalDamage = 0;\nTotalDamage += DamageThisMatch;",
    pitfalls: ["Usar por padrao quando int32 ja basta.", "Confundir capacidade maior com suporte a casas decimais."],
    related: ["int32", "double", "fstring"],
  },
  {
    slug: "double",
    title: "double",
    category: "Tipos e Variaveis",
    summary: "Tipo numerico com casas decimais e mais precisao que float. Em Unreal moderna, muitos calculos internos podem usar precisao maior.",
    syntax: "double Distance = 1250.75;",
    returns: "Um numero decimal de dupla precisao.",
    useWhen: "Use quando precisa de mais precisao numerica, coordenadas grandes, calculos acumulados ou APIs que pedem double.",
    example: "double ExactTime = 0.0;\nExactTime += DeltaSeconds;",
    pitfalls: ["Misturar com float sem conversao consciente.", "Usar para gameplay simples onde float e suficiente e mais comum."],
    related: ["float", "fvector", "deltatime"],
  },
  {
    slug: "size-t",
    title: "size_t",
    category: "Tipos e Variaveis",
    summary: "Tipo inteiro sem sinal usado pelo C++ para tamanhos e contagens de memoria/containers padrao.",
    syntax: "size_t Length = Items.size();",
    returns: "Um inteiro sem sinal grande o bastante para representar tamanhos em memoria.",
    useWhen: "Use ao lidar com APIs da biblioteca padrao C++ que retornam size_t.",
    example: "for (size_t Index = 0; Index < Items.size(); ++Index)\n{\n  // usar Items[Index]\n}",
    pitfalls: ["Comparar diretamente com int32 e criar avisos ou bugs de signed/unsigned.", "Subtrair abaixo de zero em tipo sem sinal."],
    related: ["int32", "tarray", "for-loop"],
  },
  {
    slug: "bool",
    title: "bool",
    category: "Tipos e Variaveis",
    summary: "Tipo verdadeiro/falso usado para flags, condicoes e estados.",
    syntax: "bool bIsOpen = false;",
    returns: "true ou false.",
    useWhen: "Use para guardar estados binarios como ativo/inativo, pulando/no chao, coletado/nao coletado.",
    example: "if (bCanMove)\n{\n  AddActorWorldOffset(Delta);\n}",
    pitfalls: ["Na Unreal, nomes booleanos geralmente usam prefixo b.", "Criar varios bools quando um enum deixaria estados mais claros."],
    related: ["if", "uenum"],
  },
  {
    slug: "char",
    title: "char",
    category: "Tipos e Variaveis",
    summary: "Tipo C++ para um caractere ou byte pequeno. Em Unreal, texto de jogo quase sempre usa FString, FText ou FName em vez de char cru.",
    syntax: "char Letter = 'A';",
    returns: "Um valor de caractere/byte.",
    useWhen: "Use em codigo C++ baixo nivel ou APIs que pedem char. Para texto visivel ao jogador, prefira FText.",
    example: "char Initial = 'P';",
    pitfalls: ["Usar char para textos completos.", "Confundir char com TCHAR usado por macros como TEXT()."],
    related: ["fstring", "ftext", "text-macro"],
  },
  {
    slug: "void",
    title: "void",
    category: "Tipos e Variaveis",
    summary: "Indica ausencia de retorno em uma funcao. Uma funcao void executa uma acao, mas nao devolve valor.",
    syntax: "void Collect();",
    useWhen: "Use quando a funcao muda estado, chama outra API ou dispara efeito sem precisar retornar resultado.",
    example: "void APickup::Collect()\n{\n  Destroy();\n}",
    pitfalls: ["Tentar usar o resultado de uma funcao void em uma expressao.", "Usar void quando seria melhor retornar bool para indicar sucesso/falha."],
    related: ["function-declaration", "return", "destroy"],
  },
  {
    slug: "auto",
    title: "auto",
    category: "Tipos e Variaveis",
    summary: "Pede para o compilador deduzir o tipo da variavel a partir do valor inicial.",
    syntax: "auto Location = GetActorLocation();",
    useWhen: "Use quando o tipo e obvio pelo lado direito ou muito longo, sem esconder informacao importante.",
    example: "auto* World = GetWorld();\nif (World)\n{\n  // usar World\n}",
    pitfalls: ["Esconder tipos importantes de quem esta lendo.", "Usar auto sem inicializador valido."],
    related: ["getactorlocation", "getworld", "pointer-arrow"],
  },
  {
    slug: "const",
    title: "const",
    category: "Tipos e Variaveis",
    summary: "Marca um valor ou funcao como nao modificavel naquele contexto. Ajuda a proteger dados e comunicar intencao.",
    syntax: "const float Speed = 300.0f;",
    useWhen: "Use para valores que nao devem mudar, parametros lidos sem alteracao e funcoes que nao modificam o objeto.",
    example: "float GetHealthPercent() const\n{\n  return CurrentHealth / MaxHealth;\n}",
    pitfalls: ["Achar que const torna o objeto imutavel em todos os lugares.", "Remover const para corrigir erro sem entender quem esta modificando o valor."],
    related: ["float", "return", "blueprintpure"],
  },
  {
    slug: "enum-class",
    title: "enum class",
    category: "Tipos e Variaveis",
    summary: "Tipo C++ para escolhas nomeadas e fechadas. Em Unreal, costuma aparecer junto de UENUM para uso no editor e Blueprint.",
    syntax: "enum class EDoorState : uint8 { Closed, Open };",
    useWhen: "Use quando existem estados ou opcoes finitas, como arma equipada, estado de porta ou tipo de dano.",
    example: "UENUM(BlueprintType)\nenum class EDoorState : uint8\n{\n  Closed,\n  Open\n};",
    pitfalls: ["Usar varios bools quando um enum deixaria estados impossiveis de representar.", "Esquecer o prefixo do enum ao comparar valores."],
    related: ["uenum", "uint8", "bool"],
  },
  {
    slug: "for-loop",
    title: "for",
    category: "C++ Base",
    summary: "Estrutura de repeticao usada para executar um bloco varias vezes, normalmente com contador ou indice.",
    syntax: "for (int32 Index = 0; Index < Count; ++Index) { ... }",
    useWhen: "Use para percorrer indices, repetir uma acao quantidade conhecida de vezes ou iterar containers.",
    example: "for (int32 Index = 0; Index < 3; ++Index)\n{\n  UE_LOG(LogTemp, Warning, TEXT(\"Index: %d\"), Index);\n}",
    pitfalls: ["Errar a condicao de parada e acessar indice invalido.", "Modificar o contador dentro do bloco sem necessidade."],
    related: ["int32", "tarray", "ue-log"],
  },
  {
    slug: "return",
    title: "return",
    category: "Funcoes C++",
    summary: "Encerra uma funcao e, quando a funcao tem tipo de retorno, devolve um valor para quem chamou.",
    syntax: "return Value;",
    useWhen: "Use para entregar resultado, sair cedo de uma funcao ou interromper execucao quando uma validacao falha.",
    example: "if (!TargetActor)\n{\n  return false;\n}\nreturn true;",
    pitfalls: ["Retornar valor em funcao void.", "Esquecer return em funcao que promete devolver um tipo."],
    related: ["bool", "void", "if"],
  },
  {
    slug: "function-declaration",
    title: "Declaracao de funcao",
    category: "Funcoes C++",
    summary: "Define nome, retorno e parametros de uma funcao. Em Unreal, declaracoes costumam ficar no .h e implementacoes no .cpp.",
    syntax: "float GetHealthPercent() const;",
    returns: "Depende do tipo antes do nome da funcao.",
    useWhen: "Use para expor uma acao ou consulta reutilizavel dentro da classe.",
    example: "UFUNCTION(BlueprintCallable)\nvoid OpenDoor();",
    pitfalls: ["Assinatura no .h nao bater com a implementacao no .cpp.", "Esquecer const quando a funcao so consulta estado."],
    related: ["parameters", "return", "ufunction"],
  },
  {
    slug: "parameters",
    title: "Parametros",
    category: "Funcoes C++",
    summary: "Valores que uma funcao recebe para executar seu trabalho. Podem ser passados por valor, ponteiro ou referencia.",
    syntax: "void SetSpeed(float NewSpeed);",
    useWhen: "Use para tornar funcoes reutilizaveis sem depender de valores fixos dentro delas.",
    example: "void ApplyDamage(float Amount)\n{\n  Health -= Amount;\n}",
    pitfalls: ["Passar objetos grandes por valor sem necessidade.", "Modificar parametro quando a funcao deveria apenas ler."],
    related: ["float", "const", "function-declaration"],
  },
  {
    slug: "include",
    title: "#include",
    category: "Arquivos C++",
    summary: "Instrucao de pre-processador que permite usar declaracoes vindas de outro arquivo header.",
    syntax: "#include \"GameFramework/Actor.h\"",
    useWhen: "Use quando seu arquivo precisa conhecer uma classe, funcao, struct ou macro declarada em outro header.",
    example: "#include \"CoreMinimal.h\"\n#include \"GameFramework/Actor.h\"\n#include \"MyActor.generated.h\"",
    pitfalls: ["Colocar include desnecessario no .h e aumentar tempo de compilacao.", "Nao deixar .generated.h como ultimo include em headers Unreal."],
    related: ["generated-h", "header-cpp", "uclass"],
  },
  {
    slug: "header-cpp",
    title: ".h e .cpp",
    category: "Arquivos C++",
    summary: "O .h normalmente declara a interface da classe; o .cpp implementa o comportamento.",
    syntax: "MyActor.h / MyActor.cpp",
    useWhen: "Use .h para declarar membros que outros arquivos precisam conhecer e .cpp para escrever a logica.",
    example: "// MyActor.h\nvoid OpenDoor();\n\n// MyActor.cpp\nvoid AMyActor::OpenDoor()\n{\n  // logica\n}",
    pitfalls: ["Implementar funcao no .cpp com assinatura diferente do .h.", "Colocar logica demais no header sem necessidade."],
    related: ["include", "function-declaration", "generated-h"],
  },
  {
    slug: "if",
    title: "if",
    category: "C++ Base",
    summary: "Executa um bloco apenas se uma condicao for verdadeira.",
    syntax: "if (Condition) { ... }",
    useWhen: "Use para validar estados antes de executar a logica.",
    example: "if (OtherActor != nullptr)\n{\n  UE_LOG(LogTemp, Warning, TEXT(\"Overlap\"));\n}",
    pitfalls: ["Usar = em vez de == em comparacoes.", "Nao tratar ponteiros nulos antes de usar."],
    related: ["bool", "nullptr", "cast"],
  },
  {
    slug: "nullptr",
    title: "nullptr",
    category: "C++ Base",
    summary: "Valor que representa ponteiro vazio. Ajuda a saber se uma referencia para objeto existe.",
    syntax: "if (ActorPtr != nullptr) { ... }",
    useWhen: "Use antes de acessar objetos que podem nao existir.",
    example: "if (TargetActor)\n{\n  TargetActor->Destroy();\n}",
    pitfalls: ["Acessar um ponteiro nulo causa crash.", "Assumir que uma busca sempre retorna objeto."],
    related: ["if", "cast", "getworld"],
  },
  {
    slug: "pointer-arrow",
    title: "Ponteiro e operador ->",
    category: "Operadores C++",
    summary: "Ponteiros apontam para objetos. O operador -> acessa membros do objeto apontado.",
    syntax: "ActorPtr->Destroy();",
    useWhen: "Use quando uma API retorna ponteiro, como GetWorld(), Cast ou componentes.",
    example: "AActor* Owner = GetOwner();\nif (Owner)\n{\n  Owner->SetActorHiddenInGame(true);\n}",
    pitfalls: ["Usar . em ponteiro quando deveria usar ->.", "Nao verificar se o ponteiro e valido."],
    related: ["nullptr", "cast", "getowner"],
  },
  {
    slug: "assignment-operator",
    title: "Operador =",
    category: "Operadores C++",
    summary: "Atribui um valor a uma variavel. Nao compara; ele troca o conteudo do lado esquerdo.",
    syntax: "Health = 100.0f;",
    useWhen: "Use para definir estado inicial, atualizar variaveis ou guardar resultado de uma funcao.",
    example: "FVector Location = GetActorLocation();",
    pitfalls: ["Usar = dentro de if quando queria comparar com ==.", "Atribuir valor sem perceber que esta sobrescrevendo estado anterior."],
    related: ["equality-operator", "float", "getactorlocation"],
  },
  {
    slug: "equality-operator",
    title: "Operadores == e !=",
    category: "Operadores C++",
    summary: "Comparam dois valores. == verifica igualdade; != verifica diferenca.",
    syntax: "if (Count == 0) { ... }",
    returns: "bool.",
    useWhen: "Use em condicoes para comparar estados, ponteiros, enums e valores simples.",
    example: "if (CurrentState != EDoorState::Open)\n{\n  OpenDoor();\n}",
    pitfalls: ["Confundir == com =.", "Comparar floats esperando igualdade exata em calculos com casas decimais."],
    related: ["assignment-operator", "if", "enum-class"],
  },
  {
    slug: "logical-operators",
    title: "Operadores &&, || e !",
    category: "Operadores C++",
    summary: "Combinam ou invertem condicoes booleanas. && exige tudo verdadeiro; || aceita pelo menos uma condicao; ! inverte.",
    syntax: "if (bAlive && !bStunned) { ... }",
    returns: "bool.",
    useWhen: "Use para validar multiplas regras antes de executar uma acao.",
    example: "if (TargetActor && !bIsCollected)\n{\n  Collect();\n}",
    pitfalls: ["Criar condicoes longas demais sem quebrar em variaveis com nome.", "Esquecer parenteses quando mistura && e ||."],
    related: ["bool", "if", "nullptr"],
  },
  {
    slug: "increment-operators",
    title: "Operadores ++ e +=",
    category: "Operadores C++",
    summary: "Atualizam valores numericos. ++ soma 1; += soma um valor especifico ao valor atual.",
    syntax: "Count++;\nScore += 10;",
    useWhen: "Use para contadores, pontuacao, acumuladores e progresso incremental.",
    example: "Attempts++;\nRunningTime += DeltaTime;",
    pitfalls: ["Atualizar valores dentro de Tick sem DeltaTime quando deveria ser tempo.", "Confundir ++Index e Index++ em expressoes complexas."],
    related: ["int32", "float", "deltatime"],
  },
  {
    slug: "scope-resolution",
    title: "Operador ::",
    category: "Operadores C++",
    summary: "Acessa algo dentro de um escopo, como classe, namespace ou enum class.",
    syntax: "AMyActor::BeginPlay()",
    useWhen: "Use em implementacoes de metodos, valores de enum class e membros estaticos.",
    example: "void AMyActor::BeginPlay()\n{\n  Super::BeginPlay();\n}",
    pitfalls: ["Usar . ou -> quando esta implementando funcao da classe.", "Esquecer o nome da classe antes da funcao no .cpp."],
    related: ["function-declaration", "beginplay", "enum-class"],
  },
  {
    slug: "uclass",
    title: "UCLASS()",
    category: "Unreal Macros",
    summary: "Registra uma classe C++ no sistema de reflexao da Unreal, permitindo que o engine conheca essa classe.",
    syntax: "UCLASS()\nclass AMyActor : public AActor",
    useWhen: "Use em classes Unreal que herdam de UObject, AActor, UActorComponent e similares.",
    example: "UCLASS()\nclass MYGAME_API AFloatingPickup : public AActor\n{\n  GENERATED_BODY()\n};",
    pitfalls: ["Esquecer GENERATED_BODY dentro da classe.", "Colocar UCLASS em classe C++ comum que nao herda de UObject."],
    related: ["generated-body", "aactor", "uobject"],
  },
  {
    slug: "generated-body",
    title: "GENERATED_BODY()",
    category: "Unreal Macros",
    summary: "Insere codigo gerado pela Unreal Header Tool para reflexao, serializacao e integracao com o engine.",
    syntax: "GENERATED_BODY()",
    useWhen: "Use dentro de classes, structs e interfaces Unreal marcadas com macros como UCLASS ou USTRUCT.",
    example: "UCLASS()\nclass AMyActor : public AActor\n{\n  GENERATED_BODY()\n};",
    pitfalls: ["Remover ou mover para lugar invalido quebra compilacao.", "Esquecer include do arquivo .generated.h."],
    related: ["uclass", "ustruct", "generated-h"],
  },
  {
    slug: "generated-h",
    title: "Arquivo .generated.h",
    category: "Unreal Macros",
    summary: "Header gerado pela Unreal Header Tool. Deve ser o ultimo include no arquivo .h.",
    syntax: "#include \"MyActor.generated.h\"",
    useWhen: "Use em headers com UCLASS, USTRUCT, UENUM, UINTERFACE ou macros refletidas.",
    example: "#include \"CoreMinimal.h\"\n#include \"GameFramework/Actor.h\"\n#include \"MyActor.generated.h\"",
    pitfalls: ["Nao deixar o .generated.h como ultimo include.", "Nome do generated nao bater com o nome do arquivo."],
    related: ["uclass", "generated-body", "include"],
  },
  {
    slug: "uproperty",
    title: "UPROPERTY()",
    category: "Unreal Macros",
    summary: "Registra uma variavel no sistema de reflexao da Unreal. Permite aparecer no editor, em Blueprints, serializar e participar do GC.",
    syntax: "UPROPERTY(EditAnywhere, BlueprintReadOnly, Category=\"Pickup\")\nfloat RotationSpeed;",
    useWhen: "Use para variaveis que precisam aparecer no editor, Blueprint, salvar estado ou referenciar UObject com seguranca.",
    example: "UPROPERTY(EditAnywhere, BlueprintReadOnly, Category=\"Movement\")\nfloat MoveSpeed = 300.0f;",
    pitfalls: ["Esquecer o tipo da variavel apos a macro.", "Nao usar UPROPERTY em ponteiros para UObject que precisam ser rastreados."],
    related: ["editanywhere", "blueprintreadonly", "category", "uobject"],
  },
  {
    slug: "ufunction",
    title: "UFUNCTION()",
    category: "Unreal Macros",
    summary: "Registra uma funcao para reflexao. Pode expor a funcao para Blueprint, eventos, RPCs e binding de delegates.",
    syntax: "UFUNCTION(BlueprintCallable)\nvoid ActivatePickup();",
    useWhen: "Use quando uma funcao precisa ser chamada por Blueprint, editor, rede ou sistema de eventos da Unreal.",
    example: "UFUNCTION(BlueprintCallable, Category=\"Pickup\")\nvoid Collect();",
    pitfalls: ["Assinatura invalida para Blueprint.", "Esquecer UFUNCTION em callbacks de overlap que usam AddDynamic."],
    related: ["blueprintcallable", "blueprintimplementableevent", "adddynamic"],
  },
  {
    slug: "ustruct",
    title: "USTRUCT()",
    category: "Unreal Macros",
    summary: "Registra uma struct no sistema de reflexao. Util para dados agrupados que podem aparecer no editor ou Blueprint.",
    syntax: "USTRUCT(BlueprintType)\nstruct FInventoryItem { ... };",
    useWhen: "Use para modelar dados pequenos como stats, configuracoes, itens e resultados.",
    example: "USTRUCT(BlueprintType)\nstruct FWeaponStats\n{\n  GENERATED_BODY()\n\n  UPROPERTY(EditAnywhere)\n  float Damage = 10.0f;\n};",
    pitfalls: ["Esquecer GENERATED_BODY dentro da struct.", "Colocar logica pesada em struct que deveria ser classe."],
    related: ["generated-body", "blueprinttype", "uproperty"],
  },
  {
    slug: "uenum",
    title: "UENUM()",
    category: "Unreal Macros",
    summary: "Registra um enum no sistema de reflexao para representar estados nomeados no C++ e Blueprint.",
    syntax: "UENUM(BlueprintType)\nenum class EWeaponState : uint8 { ... };",
    useWhen: "Use quando existem opcoes finitas, como estados, tipos de dano ou modos de interacao.",
    example: "UENUM(BlueprintType)\nenum class EDoorState : uint8\n{\n  Closed,\n  Open\n};",
    pitfalls: ["Usar muitos bools onde enum deixaria mais claro.", "Esquecer BlueprintType quando precisa usar em Blueprint."],
    related: ["bool", "blueprinttype"],
  },
  {
    slug: "editanywhere",
    title: "EditAnywhere",
    category: "Specifiers",
    summary: "Permite editar a propriedade no editor tanto no Blueprint/class default quanto em instancias no mapa.",
    syntax: "UPROPERTY(EditAnywhere)",
    useWhen: "Use para valores de gameplay ajustaveis no editor.",
    example: "UPROPERTY(EditAnywhere, Category=\"Movement\")\nfloat RotationSpeed = 90.0f;",
    pitfalls: ["Expor tudo sem criterio deixa o Details baguncado.", "Usar quando o valor deveria ser calculado e nao editado."],
    related: ["uproperty", "editdefaultsOnly", "visibleanywhere"],
  },
  {
    slug: "editdefaultsonly",
    title: "EditDefaultsOnly",
    category: "Specifiers",
    summary: "Permite editar a propriedade apenas nos defaults da classe/Blueprint, nao em cada instancia colocada no mapa.",
    syntax: "UPROPERTY(EditDefaultsOnly)",
    useWhen: "Use para configuracoes padrao que nao devem variar por instancia.",
    example: "UPROPERTY(EditDefaultsOnly, Category=\"Combat\")\nfloat BaseDamage = 25.0f;",
    pitfalls: ["Usar quando voce precisa ajustar cada instancia no level.", "Confundir com VisibleDefaultsOnly, que nao permite editar."],
    related: ["editanywhere", "visibleanywhere", "uproperty"],
  },
  {
    slug: "visibleanywhere",
    title: "VisibleAnywhere",
    category: "Specifiers",
    summary: "Mostra a propriedade no editor, mas nao permite editar diretamente.",
    syntax: "UPROPERTY(VisibleAnywhere)",
    useWhen: "Use para componentes criados em C++ ou valores que voce quer inspecionar sem alterar.",
    example: "UPROPERTY(VisibleAnywhere)\nUStaticMeshComponent* Mesh;",
    pitfalls: ["Esperar conseguir editar o valor no Details.", "Usar EditAnywhere em componente que deveria ser somente visivel."],
    related: ["createdefaultsubobject", "ustaticmeshcomponent", "uproperty"],
  },
  {
    slug: "blueprintreadonly",
    title: "BlueprintReadOnly",
    category: "Specifiers",
    summary: "Permite que Blueprints leiam a propriedade, mas nao escrevam nela diretamente.",
    syntax: "UPROPERTY(BlueprintReadOnly)",
    useWhen: "Use quando Blueprint precisa consultar um valor controlado pelo C++.",
    example: "UPROPERTY(BlueprintReadOnly, Category=\"State\")\nbool bIsCollected = false;",
    pitfalls: ["Achar que bloqueia mudancas no C++; ele bloqueia escrita direta no Blueprint.", "Usar BlueprintReadWrite para estado que deveria ser protegido."],
    related: ["blueprintreadwrite", "uproperty"],
  },
  {
    slug: "blueprintreadwrite",
    title: "BlueprintReadWrite",
    category: "Specifiers",
    summary: "Permite que Blueprints leiam e alterem a propriedade.",
    syntax: "UPROPERTY(BlueprintReadWrite)",
    useWhen: "Use quando designers precisam ajustar o valor durante logica visual.",
    example: "UPROPERTY(EditAnywhere, BlueprintReadWrite, Category=\"Movement\")\nfloat MoveSpeed = 600.0f;",
    pitfalls: ["Expor escrita demais pode quebrar invariantes do C++.", "Usar em valores que deveriam mudar por funcao controlada."],
    related: ["blueprintreadonly", "uproperty"],
  },
  {
    slug: "blueprintcallable",
    title: "BlueprintCallable",
    category: "Specifiers",
    summary: "Permite chamar uma funcao C++ a partir de Blueprints.",
    syntax: "UFUNCTION(BlueprintCallable)",
    useWhen: "Use para criar acoes de gameplay acessiveis no Blueprint.",
    example: "UFUNCTION(BlueprintCallable, Category=\"Door\")\nvoid OpenDoor();",
    pitfalls: ["Colocar logica insegura aberta para qualquer Blueprint.", "Nao marcar Category e deixar organizacao ruim."],
    related: ["ufunction", "blueprintpure", "category"],
  },
  {
    slug: "blueprintpure",
    title: "BlueprintPure",
    category: "Specifiers",
    summary: "Expõe uma funcao para Blueprint como consulta sem execucao visual, ideal para getters e calculos sem efeito colateral.",
    syntax: "UFUNCTION(BlueprintPure)",
    useWhen: "Use para funcoes que apenas retornam informacao e nao alteram estado.",
    example: "UFUNCTION(BlueprintPure, Category=\"Health\")\nfloat GetHealthPercent() const;",
    pitfalls: ["Marcar como Pure uma funcao que altera estado.", "Fazer operacoes caras em funcao Pure chamada muitas vezes."],
    related: ["blueprintcallable", "const", "ufunction"],
  },
  {
    slug: "category",
    title: "Category",
    category: "Specifiers",
    summary: "Organiza propriedades e funcoes em grupos no editor e no Blueprint.",
    syntax: "Category=\"Pickup\"",
    useWhen: "Use para deixar Details e Blueprint organizados por assunto.",
    example: "UPROPERTY(EditAnywhere, Category=\"Pickup|Movement\")\nfloat FloatSpeed;",
    pitfalls: ["Categorias inconsistentes deixam o editor confuso.", "Criar categorias demais para poucos campos."],
    related: ["uproperty", "ufunction", "editanywhere"],
  },
  {
    slug: "aactor",
    title: "AActor",
    category: "Tipos Unreal",
    summary: "Classe base para objetos que podem existir no mundo da Unreal: pickups, portas, inimigos, spawners e muito mais.",
    syntax: "class AMyActor : public AActor",
    useWhen: "Use quando o objeto precisa ser colocado, transformado, spawnado ou destruido no mundo.",
    example: "AActor* Spawned = GetWorld()->SpawnActor<AActor>(ActorClass, Location, Rotation);",
    pitfalls: ["Usar AActor para dados que nao precisam existir no mundo.", "Esquecer que Actors tem ciclo de vida proprio."],
    related: ["beginplay", "tick", "spawnactor", "destroy"],
  },
  {
    slug: "uobject",
    title: "UObject",
    category: "Tipos Unreal",
    summary: "Base de muitos objetos da Unreal que participam de reflexao, serializacao e garbage collection.",
    syntax: "class UMyObject : public UObject",
    useWhen: "Use para objetos de dados/sistemas que nao precisam de transform no mundo.",
    example: "UPROPERTY()\nUObject* CachedObject;",
    pitfalls: ["Criar UObject com new comum em vez de usar APIs da Unreal.", "Nao marcar referencias com UPROPERTY quando precisam sobreviver ao GC."],
    related: ["uproperty", "newobject", "memory"],
  },
  {
    slug: "fvector",
    title: "FVector",
    category: "Tipos Unreal",
    summary: "Representa um vetor 3D com X, Y e Z. Usado para posicao, direcao, velocidade e escala.",
    syntax: "FVector Location(0.0f, 0.0f, 100.0f);",
    returns: "Um valor com componentes X, Y e Z.",
    useWhen: "Use para qualquer dado espacial em 3D.",
    example: "FVector NewLocation = InitialLocation;\nNewLocation.Z += 50.0f;\nSetActorLocation(NewLocation);",
    pitfalls: ["Confundir eixo Z com altura.", "Usar vetor sem normalizar quando ele representa direcao."],
    related: ["getactorlocation", "setactorlocation", "fmath"],
  },
  {
    slug: "frotator",
    title: "FRotator",
    category: "Tipos Unreal",
    summary: "Representa rotacao em graus usando Pitch, Yaw e Roll.",
    syntax: "FRotator Rotation(0.0f, 90.0f, 0.0f);",
    returns: "Uma rotacao em graus.",
    useWhen: "Use para rotacionar Actors, componentes e spawns de forma legivel.",
    example: "AddActorLocalRotation(FRotator(0.0f, RotationSpeed * DeltaTime, 0.0f));",
    pitfalls: ["Confundir Yaw com Pitch.", "Colocar virgula entre o tipo e os parenteses: FRotator,(...)." ],
    related: ["addactorlocalrotation", "setactorrotation", "deltatime"],
  },
  {
    slug: "ftransform",
    title: "FTransform",
    category: "Tipos Unreal",
    summary: "Agrupa posicao, rotacao e escala em um unico valor.",
    syntax: "FTransform Transform(Rotation, Location, Scale);",
    useWhen: "Use para spawn, anexos, conversoes de espaco e manipulacao completa de transform.",
    example: "FTransform SpawnTransform(Rotation, Location);\nGetWorld()->SpawnActor<AActor>(ClassToSpawn, SpawnTransform);",
    pitfalls: ["Usar FVector/FRotator separados quando a API espera FTransform.", "Confundir espaco local e mundo."],
    related: ["spawnactor", "fvector", "frotator"],
  },
  {
    slug: "fname",
    title: "FName",
    category: "Tipos Unreal",
    summary: "Nome otimizado e imutavel usado para identificadores, sockets, rows e nomes internos.",
    syntax: "FName SocketName = TEXT(\"Muzzle\");",
    useWhen: "Use para identificadores comparados frequentemente.",
    example: "Mesh->GetSocketLocation(FName(\"Muzzle\"));",
    pitfalls: ["Usar FString para comparacoes de identificadores repetidas.", "Esperar que FName preserve caixa de texto para exibicao."],
    related: ["fstring", "ftext", "text-macro"],
  },
  {
    slug: "fstring",
    title: "FString",
    category: "Tipos Unreal",
    summary: "String mutavel da Unreal, boa para montar textos, paths e logs.",
    syntax: "FString Name = TEXT(\"Player\");",
    useWhen: "Use quando precisa manipular texto em C++.",
    example: "FString Message = FString::Printf(TEXT(\"Score: %d\"), Score);",
    pitfalls: ["Usar FString para texto de UI localizado.", "Confundir com FName e FText."],
    related: ["ftext", "fname", "ue-log"],
  },
  {
    slug: "ftext",
    title: "FText",
    category: "Tipos Unreal",
    summary: "Texto preparado para localizacao e exibicao ao usuario.",
    syntax: "FText Label = FText::FromString(TEXT(\"Start\"));",
    useWhen: "Use para textos de interface que podem ser localizados.",
    example: "FText ButtonLabel = FText::FromString(TEXT(\"Coletar\"));",
    pitfalls: ["Usar FString em UI que precisa traducao.", "Converter ida e volta sem necessidade."],
    related: ["fstring", "fname", "text-macro"],
  },
  {
    slug: "beginplay",
    title: "BeginPlay()",
    category: "Actor Lifecycle",
    summary: "Chamado quando o Actor entra em jogo. Ideal para inicializacao que depende do mundo ja estar rodando.",
    syntax: "virtual void BeginPlay() override;",
    useWhen: "Use para capturar posicao inicial, buscar referencias e iniciar logicas de runtime.",
    example: "void AFloatingPickup::BeginPlay()\n{\n  Super::BeginPlay();\n  InitialLocation = GetActorLocation();\n}",
    pitfalls: ["Esquecer Super::BeginPlay().", "Colocar logica no construtor que depende do mundo."],
    related: ["constructor", "getactorlocation", "super"],
  },
  {
    slug: "tick",
    title: "Tick(float DeltaTime)",
    category: "Actor Lifecycle",
    summary: "Chamado a cada frame quando o Tick esta habilitado. Usado para movimento continuo, timers manuais e atualizacoes visuais.",
    syntax: "virtual void Tick(float DeltaTime) override;",
    useWhen: "Use para logica que precisa atualizar continuamente por frame.",
    example: "void AMyActor::Tick(float DeltaTime)\n{\n  Super::Tick(DeltaTime);\n  RunningTime += DeltaTime;\n}",
    pitfalls: ["Usar Tick para tudo e desperdiçar performance.", "Esquecer de multiplicar movimento por DeltaTime."],
    related: ["deltatime", "primaryactortick", "super"],
  },
  {
    slug: "deltatime",
    title: "DeltaTime",
    category: "Actor Lifecycle",
    summary: "Tempo em segundos desde o ultimo frame. Garante movimento independente do FPS.",
    syntax: "Speed * DeltaTime",
    returns: "Um float com a duracao do frame.",
    useWhen: "Use em movimentos, rotacoes e acumuladores de tempo dentro do Tick.",
    example: "AddActorLocalRotation(FRotator(0.0f, RotationSpeed * DeltaTime, 0.0f));",
    pitfalls: ["Somar velocidade diretamente sem DeltaTime.", "Usar DeltaTime como tempo total em vez de acumular."],
    related: ["tick", "frotator", "fmath-sin"],
  },
  {
    slug: "super",
    title: "Super::",
    category: "Actor Lifecycle",
    summary: "Chama a implementacao da classe base. Mantem o comportamento original da Unreal antes/depois da sua logica.",
    syntax: "Super::BeginPlay();",
    useWhen: "Use em overrides como BeginPlay, Tick e SetupPlayerInputComponent.",
    example: "void AMyPawn::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)\n{\n  Super::SetupPlayerInputComponent(PlayerInputComponent);\n}",
    pitfalls: ["Esquecer Super pode quebrar comportamento base.", "Chamar Super no lugar errado quando a ordem importa."],
    related: ["override", "beginplay", "tick"],
  },
  {
    slug: "primaryactortick",
    title: "PrimaryActorTick.bCanEverTick",
    category: "Actor Lifecycle",
    summary: "Define se um Actor pode receber Tick.",
    syntax: "PrimaryActorTick.bCanEverTick = true;",
    useWhen: "Use no construtor quando o Actor precisa atualizar a cada frame.",
    example: "AFloatingPickup::AFloatingPickup()\n{\n  PrimaryActorTick.bCanEverTick = true;\n}",
    pitfalls: ["Habilitar Tick sem necessidade.", "Esperar Tick rodar quando bCanEverTick esta false."],
    related: ["tick", "constructor"],
  },
  {
    slug: "getactorlocation",
    title: "GetActorLocation()",
    category: "Transform",
    summary: "Retorna a posicao atual do Actor no mundo.",
    syntax: "FVector Location = GetActorLocation();",
    returns: "FVector com X, Y e Z no mundo.",
    useWhen: "Use para ler onde o Actor esta antes de mover, calcular distancia ou salvar posicao inicial.",
    example: "InitialLocation = GetActorLocation();",
    pitfalls: ["Chamar no construtor esperando posicao final no mundo.", "Confundir posicao mundial com local."],
    related: ["setactorlocation", "fvector", "beginplay"],
  },
  {
    slug: "setactorlocation",
    title: "SetActorLocation()",
    category: "Transform",
    summary: "Move o Actor para uma posicao absoluta no mundo.",
    syntax: "SetActorLocation(NewLocation);",
    returns: "bool indicando se o movimento ocorreu em algumas sobrecargas.",
    useWhen: "Use quando voce sabe a posicao final desejada.",
    example: "FVector NewLocation = InitialLocation;\nNewLocation.Z += ZOffset;\nSetActorLocation(NewLocation);",
    pitfalls: ["Usar para movimento relativo quando AddActorWorldOffset seria mais claro.", "Ignorar colisao/sweep quando necessario."],
    related: ["getactorlocation", "addactorworldoffset", "fvector"],
  },
  {
    slug: "addactorworldoffset",
    title: "AddActorWorldOffset()",
    category: "Transform",
    summary: "Move o Actor por um deslocamento relativo em espaco mundial.",
    syntax: "AddActorWorldOffset(Delta);",
    useWhen: "Use para mover o Actor uma quantidade a partir da posicao atual.",
    example: "AddActorWorldOffset(FVector(100.0f * DeltaTime, 0.0f, 0.0f));",
    pitfalls: ["Confundir offset mundial com local.", "Mover sem DeltaTime dentro do Tick."],
    related: ["setactorlocation", "deltatime", "fvector"],
  },
  {
    slug: "addactorlocalrotation",
    title: "AddActorLocalRotation()",
    category: "Transform",
    summary: "Aplica uma rotacao incremental no espaco local do Actor.",
    syntax: "AddActorLocalRotation(FRotator DeltaRotation);",
    useWhen: "Use para girar continuamente um Actor em torno dos proprios eixos.",
    example: "AddActorLocalRotation(FRotator(0.0f, RotationSpeed * DeltaTime, 0.0f));",
    pitfalls: ["Esquecer DeltaTime.", "Confundir rotacao local com rotacao mundial."],
    related: ["frotator", "deltatime", "setactorrotation"],
  },
  {
    slug: "setactorrotation",
    title: "SetActorRotation()",
    category: "Transform",
    summary: "Define a rotacao absoluta do Actor.",
    syntax: "SetActorRotation(NewRotation);",
    useWhen: "Use quando precisa apontar o Actor para uma rotacao especifica.",
    example: "SetActorRotation(FRotator(0.0f, 180.0f, 0.0f));",
    pitfalls: ["Usar SetActorRotation para rotacao incremental quando AddActorLocalRotation e mais adequado.", "Confundir graus com radianos."],
    related: ["frotator", "addactorlocalrotation"],
  },
  {
    slug: "fmath-sin",
    title: "FMath::Sin()",
    category: "Math",
    summary: "Retorna o seno de um valor em radianos. Muito usado para oscilacao suave.",
    syntax: "float Wave = FMath::Sin(Value);",
    returns: "float entre -1.0 e 1.0.",
    useWhen: "Use para flutuacao, pulso, onda, movimento periodico e efeitos suaves.",
    example: "RunningTime += DeltaTime;\nfloat ZOffset = FMath::Sin(RunningTime * FloatSpeed) * FloatAmplitude;",
    pitfalls: ["Passar amplitude dentro do Sin em vez de multiplicar o resultado.", "Esquecer que o valor de entrada e em radianos."],
    related: ["deltatime", "float", "setactorlocation"],
  },
  {
    slug: "fmath-clamp",
    title: "FMath::Clamp()",
    category: "Math",
    summary: "Limita um valor entre minimo e maximo.",
    syntax: "FMath::Clamp(Value, Min, Max)",
    returns: "Valor dentro do intervalo informado.",
    useWhen: "Use para impedir vida negativa, stamina acima do limite ou valores fora da faixa.",
    example: "Health = FMath::Clamp(Health - Damage, 0.0f, MaxHealth);",
    pitfalls: ["Inverter minimo e maximo.", "Usar para corrigir sintoma de uma formula errada sem entender a causa."],
    related: ["float", "fmath-lerp"],
  },
  {
    slug: "fmath-lerp",
    title: "FMath::Lerp()",
    category: "Math",
    summary: "Interpola entre dois valores usando Alpha entre 0 e 1.",
    syntax: "FMath::Lerp(A, B, Alpha)",
    returns: "Valor entre A e B.",
    useWhen: "Use para transicoes suaves de valores, posicoes e escalas.",
    example: "float Current = FMath::Lerp(StartValue, TargetValue, Alpha);",
    pitfalls: ["Usar Alpha fora de 0..1 sem querer.", "Esperar que Lerp sozinho faca suavizacao baseada em tempo."],
    related: ["fmath-clamp", "vinterp-to"],
  },
  {
    slug: "vinterp-to",
    title: "FMath::VInterpTo()",
    category: "Math",
    summary: "Interpola um FVector em direcao a outro com velocidade dependente de DeltaTime.",
    syntax: "FMath::VInterpTo(Current, Target, DeltaTime, Speed)",
    returns: "FVector aproximado do alvo.",
    useWhen: "Use para movimento suave ate uma posicao.",
    example: "FVector NewLocation = FMath::VInterpTo(GetActorLocation(), TargetLocation, DeltaTime, 4.0f);",
    pitfalls: ["Confundir InterpSpeed com duracao exata.", "Usar em Tick sem DeltaTime correto."],
    related: ["fvector", "deltatime", "setactorlocation"],
  },
  {
    slug: "createdefaultsubobject",
    title: "CreateDefaultSubobject()",
    category: "Components",
    summary: "Cria componentes padrao no construtor de uma classe Unreal.",
    syntax: "CreateDefaultSubobject<UStaticMeshComponent>(TEXT(\"Mesh\"))",
    returns: "Ponteiro para o componente criado.",
    useWhen: "Use no construtor para montar a estrutura fixa de um Actor.",
    example: "Mesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT(\"Mesh\"));\nRootComponent = Mesh;",
    pitfalls: ["Chamar fora do construtor.", "Nao guardar o ponteiro em UPROPERTY."],
    related: ["ustaticmeshcomponent", "rootcomponent", "uproperty"],
  },
  {
    slug: "rootcomponent",
    title: "RootComponent",
    category: "Components",
    summary: "Componente raiz que define a base de transform do Actor.",
    syntax: "RootComponent = Mesh;",
    useWhen: "Use para escolher qual componente controla posicao/rotacao/escala do Actor.",
    example: "Collision = CreateDefaultSubobject<USphereComponent>(TEXT(\"Collision\"));\nRootComponent = Collision;",
    pitfalls: ["Criar componentes sem raiz clara.", "Anexar componentes antes de definir a raiz em setups confusos."],
    related: ["setupattachment", "createdefaultsubobject"],
  },
  {
    slug: "setupattachment",
    title: "SetupAttachment()",
    category: "Components",
    summary: "Anexa um componente a outro durante a construcao do Actor.",
    syntax: "Mesh->SetupAttachment(RootComponent);",
    useWhen: "Use para montar hierarquia de componentes no construtor.",
    example: "Mesh->SetupAttachment(Collision);",
    pitfalls: ["Usar AttachToComponent no construtor quando SetupAttachment e o padrao.", "Anexar a um componente nulo."],
    related: ["rootcomponent", "createdefaultsubobject"],
  },
  {
    slug: "ustaticmeshcomponent",
    title: "UStaticMeshComponent",
    category: "Components",
    summary: "Componente que exibe uma malha estatica no mundo.",
    syntax: "UStaticMeshComponent* Mesh;",
    useWhen: "Use para dar representacao visual a objetos como pickups, portas e plataformas.",
    example: "UPROPERTY(VisibleAnywhere)\nUStaticMeshComponent* Mesh;",
    pitfalls: ["Confundir componente com asset de Static Mesh.", "Nao anexar ou definir como RootComponent."],
    related: ["createdefaultsubobject", "rootcomponent", "visibleanywhere"],
  },
  {
    slug: "uspherecomponent",
    title: "USphereComponent",
    category: "Collision",
    summary: "Componente de colisao em formato de esfera, comum para areas de coleta e deteccao.",
    syntax: "USphereComponent* Collision;",
    useWhen: "Use para detectar proximidade/overlap em volta de um Actor.",
    example: "Collision = CreateDefaultSubobject<USphereComponent>(TEXT(\"Collision\"));\nCollision->SetSphereRadius(80.0f);",
    pitfalls: ["Esquecer include de Components/SphereComponent.h.", "Nao configurar eventos de overlap."],
    related: ["oncomponentbeginoverlap", "setcollisionprofileName"],
  },
  {
    slug: "setcollisionprofilename",
    title: "SetCollisionProfileName()",
    category: "Collision",
    summary: "Define um perfil de colisao preconfigurado para um componente.",
    syntax: "Component->SetCollisionProfileName(TEXT(\"OverlapAllDynamic\"));",
    useWhen: "Use para aplicar regras de colisao conhecidas sem configurar cada canal manualmente.",
    example: "Collision->SetCollisionProfileName(TEXT(\"OverlapAllDynamic\"));",
    pitfalls: ["Usar nome de profile inexistente.", "Esperar overlap sem GenerateOverlapEvents habilitado."],
    related: ["uspherecomponent", "oncomponentbeginoverlap"],
  },
  {
    slug: "oncomponentbeginoverlap",
    title: "OnComponentBeginOverlap",
    category: "Collision",
    summary: "Delegate disparado quando outro componente entra em overlap.",
    syntax: "Collision->OnComponentBeginOverlap.AddDynamic(this, &AMyActor::OnOverlap);",
    useWhen: "Use para coletaveis, triggers, areas de dano e interacoes por proximidade.",
    example: "Collision->OnComponentBeginOverlap.AddDynamic(this, &APickup::HandleOverlap);",
    pitfalls: ["Funcao callback precisa de UFUNCTION.", "Assinatura da funcao deve bater com o delegate."],
    related: ["ufunction", "adddynamic", "cast"],
  },
  {
    slug: "adddynamic",
    title: "AddDynamic()",
    category: "Collision",
    summary: "Registra uma funcao UFUNCTION em um delegate dinamico da Unreal.",
    syntax: "Delegate.AddDynamic(this, &AClass::FunctionName);",
    useWhen: "Use para conectar eventos de overlap, hit e outros delegates dinamicos.",
    example: "Collision->OnComponentBeginOverlap.AddDynamic(this, &APickup::OnOverlap);",
    pitfalls: ["Callback sem UFUNCTION nao funciona.", "Assinatura errada gera erro dificil no template."],
    related: ["ufunction", "oncomponentbeginoverlap"],
  },
  {
    slug: "cast",
    title: "Cast<T>()",
    category: "Gameplay Framework",
    summary: "Tenta converter um UObject para um tipo especifico da Unreal com seguranca.",
    syntax: "AMyCharacter* Character = Cast<AMyCharacter>(OtherActor);",
    returns: "Ponteiro do tipo desejado ou nullptr.",
    useWhen: "Use quando precisa confirmar que um Actor e de uma classe antes de acessar membros dela.",
    example: "if (AMyCharacter* Character = Cast<AMyCharacter>(OtherActor))\n{\n  Character->AddScore(1);\n}",
    pitfalls: ["Usar sem verificar nullptr.", "Fazer Cast demais quando interfaces ou delegates seriam melhor."],
    related: ["nullptr", "aactor", "interfaces"],
  },
  {
    slug: "destroy",
    title: "Destroy()",
    category: "Gameplay Framework",
    summary: "Marca um Actor para ser removido do mundo.",
    syntax: "Destroy();",
    useWhen: "Use para remover pickups coletados, projeteis expirados ou objetos descartados.",
    example: "void APickup::Collect()\n{\n  Destroy();\n}",
    pitfalls: ["Continuar usando o Actor apos chamar Destroy.", "Usar em UObject que nao e Actor."],
    related: ["aactor", "oncomponentbeginoverlap"],
  },
  {
    slug: "getworld",
    title: "GetWorld()",
    category: "Gameplay Framework",
    summary: "Retorna o mundo atual associado ao objeto.",
    syntax: "UWorld* World = GetWorld();",
    returns: "Ponteiro para UWorld ou nullptr em alguns contextos.",
    useWhen: "Use para spawnar Actors, acessar timers e consultar sistemas do mundo.",
    example: "if (UWorld* World = GetWorld())\n{\n  World->SpawnActor<AActor>(ActorClass, Location, Rotation);\n}",
    pitfalls: ["GetWorld pode ser nulo em construtores ou objetos sem mundo.", "Nao verificar antes de usar em contextos incertos."],
    related: ["spawnactor", "settimer", "nullptr"],
  },
  {
    slug: "spawnactor",
    title: "SpawnActor<T>()",
    category: "Gameplay Framework",
    summary: "Cria um Actor dinamicamente no mundo.",
    syntax: "GetWorld()->SpawnActor<AMyActor>(Class, Location, Rotation);",
    returns: "Ponteiro para o Actor criado ou nullptr.",
    useWhen: "Use para criar projeteis, inimigos, pickups e efeitos durante o jogo.",
    example: "AActor* Spawned = GetWorld()->SpawnActor<AActor>(ActorToSpawn, SpawnLocation, SpawnRotation);",
    pitfalls: ["Nao verificar se GetWorld existe.", "Spawnar classe nula.", "Confundir classe com instancia."],
    related: ["getworld", "tsubclassof", "ftransform"],
  },
  {
    slug: "tsubclassof",
    title: "TSubclassOf<T>",
    category: "Gameplay Framework",
    summary: "Tipo que guarda uma classe derivada de T, muito usado para escolher o que spawnar no editor.",
    syntax: "TSubclassOf<AActor> ActorClass;",
    useWhen: "Use quando designers precisam escolher uma classe Blueprint/C++ para spawnar.",
    example: "UPROPERTY(EditAnywhere)\nTSubclassOf<AActor> PickupClass;",
    pitfalls: ["Confundir TSubclassOf com ponteiro para instancia.", "Nao validar antes de SpawnActor."],
    related: ["spawnactor", "uproperty"],
  },
  {
    slug: "apawn",
    title: "APawn",
    category: "Gameplay Framework",
    summary: "Actor que pode ser possuido por Controller. Base para personagens e entidades controlaveis.",
    syntax: "class AMyPawn : public APawn",
    useWhen: "Use quando o objeto precisa receber controle de jogador ou IA.",
    example: "APawn* ControlledPawn = GetPawn();",
    pitfalls: ["Usar AActor quando precisa de possess/input.", "Usar APawn quando ACharacter ja oferece movimento pronto."],
    related: ["acharacter", "playercontroller", "setupplayerinputcomponent"],
  },
  {
    slug: "acharacter",
    title: "ACharacter",
    category: "Gameplay Framework",
    summary: "Pawn com CapsuleComponent, SkeletalMesh e CharacterMovementComponent prontos.",
    syntax: "class AMyCharacter : public ACharacter",
    useWhen: "Use para personagens humanoides ou entidades com movimento de personagem.",
    example: "AddMovementInput(GetActorForwardVector(), Value);",
    pitfalls: ["Recriar sistema de movimento que ACharacter ja tem.", "Usar ACharacter para objetos que nao precisam dessas features."],
    related: ["apawn", "addmovementinput", "characterMovement"],
  },
  {
    slug: "setupplayerinputcomponent",
    title: "SetupPlayerInputComponent()",
    category: "Input",
    summary: "Funcao usada em Pawn/Character para registrar bindings de input.",
    syntax: "virtual void SetupPlayerInputComponent(UInputComponent* PlayerInputComponent) override;",
    useWhen: "Use para conectar acoes e eixos do jogador ao C++.",
    example: "void AMyCharacter::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)\n{\n  Super::SetupPlayerInputComponent(PlayerInputComponent);\n}",
    pitfalls: ["Esquecer Super.", "Assumir que Actor comum recebe essa funcao."],
    related: ["apawn", "acharacter", "enhanced-input"],
  },
  {
    slug: "enhanced-input",
    title: "Enhanced Input",
    category: "Input",
    summary: "Sistema moderno de input da Unreal baseado em Input Actions e Mapping Contexts.",
    syntax: "UEnhancedInputComponent / UInputAction / UInputMappingContext",
    useWhen: "Use em projetos Unreal recentes para input configuravel e extensivel.",
    example: "EnhancedInputComponent->BindAction(MoveAction, ETriggerEvent::Triggered, this, &AMyCharacter::Move);",
    pitfalls: ["Esquecer adicionar Mapping Context ao LocalPlayerSubsystem.", "Misturar sistema antigo e Enhanced Input sem clareza."],
    related: ["setupplayerinputcomponent", "addmovementinput"],
  },
  {
    slug: "addmovementinput",
    title: "AddMovementInput()",
    category: "Input",
    summary: "Adiciona intencao de movimento a Pawns/Characters.",
    syntax: "AddMovementInput(Direction, ScaleValue);",
    useWhen: "Use em Pawn/Character para mover usando sistema de movimento.",
    example: "AddMovementInput(GetActorForwardVector(), Value);",
    pitfalls: ["Chamar em Actor que nao e Pawn/Character.", "Esperar movimento sem MovementComponent adequado."],
    related: ["acharacter", "apawn", "enhanced-input"],
  },
  {
    slug: "ue-log",
    title: "UE_LOG",
    category: "Debug",
    summary: "Macro para imprimir mensagens no Output Log da Unreal.",
    syntax: "UE_LOG(LogTemp, Warning, TEXT(\"Mensagem\"));",
    useWhen: "Use para depurar fluxo, valores e eventos durante execucao.",
    example: "UE_LOG(LogTemp, Warning, TEXT(\"Speed: %f\"), RotationSpeed);",
    pitfalls: ["Esquecer TEXT em strings literais.", "Deixar logs demais em Tick."],
    related: ["text-macro", "fstring"],
  },
  {
    slug: "text-macro",
    title: "TEXT()",
    category: "Debug",
    summary: "Macro para criar literais compatíveis com TCHAR, usados por APIs de texto da Unreal.",
    syntax: "TEXT(\"Hello\")",
    useWhen: "Use em strings literais passadas para UE_LOG, FName, FString e APIs Unreal.",
    example: "UE_LOG(LogTemp, Warning, TEXT(\"Coletado\"));",
    pitfalls: ["Passar string sem TEXT para API que espera TCHAR.", "Confundir TEXT com FText."],
    related: ["ue-log", "fstring", "fname"],
  },
  {
    slug: "drawdebugsphere",
    title: "DrawDebugSphere()",
    category: "Debug",
    summary: "Desenha uma esfera temporaria no mundo para visualizar posicoes, raios e areas.",
    syntax: "DrawDebugSphere(GetWorld(), Center, Radius, Segments, Color);",
    useWhen: "Use para enxergar areas de colisao, alvos e pontos calculados.",
    example: "DrawDebugSphere(GetWorld(), GetActorLocation(), 80.0f, 16, FColor::Green, false, 2.0f);",
    pitfalls: ["Esquecer include DrawDebugHelpers.h.", "Deixar debug visual em codigo final sem controle."],
    related: ["getworld", "fvector"],
  },
  {
    slug: "tarray",
    title: "TArray<T>",
    category: "Containers",
    summary: "Array dinamico da Unreal, equivalente comum a lista de elementos.",
    syntax: "TArray<AActor*> Actors;",
    useWhen: "Use para guardar colecoes ordenadas de itens, Actors, resultados e dados.",
    example: "TArray<AActor*> FoundActors;\nFoundActors.Add(Actor);",
    pitfalls: ["Remover enquanto itera sem cuidado.", "Guardar ponteiros UObject sem UPROPERTY quando necessario."],
    related: ["tmap", "tset", "uproperty"],
  },
  {
    slug: "tmap",
    title: "TMap<Key, Value>",
    category: "Containers",
    summary: "Mapa chave-valor da Unreal.",
    syntax: "TMap<FName, int32> Scores;",
    useWhen: "Use para associar IDs a dados, como nome de item para quantidade.",
    example: "Scores.Add(TEXT(\"Coins\"), 10);",
    pitfalls: ["Usar quando uma lista simples bastaria.", "Nao tratar chave ausente."],
    related: ["tarray", "fname"],
  },
  {
    slug: "tset",
    title: "TSet<T>",
    category: "Containers",
    summary: "Colecao de valores unicos.",
    syntax: "TSet<AActor*> VisitedActors;",
    useWhen: "Use quando precisa saber se algo ja foi visto/registrado sem duplicar.",
    example: "VisitedActors.Add(OtherActor);",
    pitfalls: ["Esperar ordem estavel dos elementos.", "Usar TSet quando precisa preservar sequencia."],
    related: ["tarray", "tmap"],
  },
  {
    slug: "upointer-gc",
    title: "UPROPERTY e Garbage Collection",
    category: "Memory",
    summary: "Referencias para UObjects marcadas com UPROPERTY sao rastreadas pelo garbage collector da Unreal.",
    syntax: "UPROPERTY()\nUObject* CachedObject;",
    useWhen: "Use para manter referencias seguras a UObjects entre frames.",
    example: "UPROPERTY()\nAActor* CurrentTarget;",
    pitfalls: ["Guardar UObject* cru sem UPROPERTY e perder referencia para o GC.", "Assumir que UPROPERTY resolve validade de Actor destruido."],
    related: ["uproperty", "uobject", "nullptr"],
  },
  {
    slug: "newobject",
    title: "NewObject<T>()",
    category: "Memory",
    summary: "Cria uma instancia de UObject gerenciada pela Unreal.",
    syntax: "NewObject<UMyObject>(Outer)",
    returns: "Ponteiro para o UObject criado.",
    useWhen: "Use para criar UObjects em runtime.",
    example: "UMyObject* Data = NewObject<UMyObject>(this);",
    pitfalls: ["Usar new/delete manual com UObject.", "Nao definir Outer adequado."],
    related: ["uobject", "upointer-gc"],
  },
];

export function findReferenceEntry(slug: string) {
  return referenceEntries.find((entry) => entry.slug === slug);
}
